#!/bin/bash

cd "$(dirname "$0")"

rm *.md
cp ../../../../${PWD##*/}/*.md .

rm CODE-OF-CONDUCT.md
rm CONTRIBUTING.md
rm LICENSE.md

mv README.md tmp
echo '---
sidebar_position: 1
---
# S3D Website
' > overview.md
cat tmp | sed -n -e '/Overview/,$p' >> overview.md
rm tmp
