#!/bin/bash

# Switch to script directory
cd "$(dirname "$0")"

# Exit on errors
set -e

# Make sure the version is correct
./s3d-version

# Build (with npm install if needed)
npm run build

# Apply to S3
s3='s3://220927-python'
aws s3 sync --delete build $s3-www-s3d-club
aws s3 sync --delete go $s3-go-s3d-club
